### ISSUE TITLE
[appserver-io/http] HTTP request parsing doen't work for URIs containing Umlauts

### ISSUE THREAD

**Issue by 2case** [appserver-io/appserver#1016]
I couldn't find where exactly the problem is, but the appserver seems to work strange on urls with umlaut filenames: `test.dev/mürks.txt` becomes `test.dev/m&uuml;rks.txt` even a rewrite rule with `<rewrite condition="-d{OR}-f{OR}-l" target="" flag="L" />` doesn't work.

**Comment by wick-ed** [comment]
Hi @2case ,
thanks for submitting this issue. We will look into it. :)

**Comment by wick-ed** [comment]
Hi @2case ,

can you further elaborate on the circumstances of this issue?
This seems to be a more complex problem that a simple Umlaut issue.

A test request done in the browser against a file `müllmänner.txt` or `test/müllmänner.txt` resolves to its content without issues.
Might it be that this is the problem of the client you are using? Or a certain configuration problem you have?

Is the URL `test.dev/m&uuml;rks.txt` automatically generated in any way? What can you see in the `appserver-access.log`?

Regards,

Bernhard

**Comment by 2case** [comment]
We develop a new neos site with the appserver as local development system on a mac os x system. I used your example setup to handle the vhost configuration. The file with the umlaut was manually created with a `touch mürks.txt` inside the `./Web` folder. Inside the `appserver-access.log` the request is shown as `127.0.0.1 - - [20/May/2016:15:37:18 +0200] "GET /m&uuml;rks.txt HTTP/1.1" 404 755 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"`. The problem is, that the appserver doesn't detect the file and forward the request to neos, where the sanitizing produce the `/m&uuml;rks.txt` result. Maybe an interesting side note is that the referrer in the related client requests look like `/m%C3%BCrks.txt` (For the favicon.ico for example)

**Comment by wick-ed** [comment]
Does this also happen if you browse the file directly, without any virtual host?
E.g. `127.0.0.1:9080/MY_APP_NAME/Web/mürks.txt`

**Comment by wick-ed** [comment]
In my tests, URL encoded Umlauts like `/m%C3%BCrks.txt` were resolved correctly. Where as `/m&uuml;rks.txt` (HTML special chars?) will not work. Whether in the appserver nor in nginx.
So why and how is an URI encoded in this way?
You might have a look at the original URI as it reaches your server and post it here.
Either send the request via e.g. CURL so you are in full control or log it before URI sanitation takes place: https://github.com/appserver-io/http/blob/master/src/AppserverIo/Http/HttpRequestParser.php#L74

Either way I am not sure where the actual problem is located.

**Comment by wick-ed** [comment]
I assume you have the latest 1.1.1? There seems to be an issue with URI normalization. I will look into this. :)

**Comment by 2case** [comment]
Correct I use the latest version

**Comment by wick-ed** [comment]
Hi @2case ,
this issue should be fixed with [this release](https://github.com/appserver-io/http/releases/tag/2.0.2). Please update the appserver-io/http package and retest.
Will close the issue, please re-open if the problem still persists after update.

Regards,
Bernhard
