### ISSUE TITLE
appserver-io-lab/mage-servlet segfaults on ob_start \Mage:run(), etc.

### ISSUE THREAD

**Issue by epet-sys** [appserver-io/appserver#1023]
I was trying to run Magento as a Servlet using appserver-io-lab/mage-servlet. 
I first ran into issues with with method isVhost being unknown. After determining, that these lines are not relevant (I'm using vhost) I commented lines 321,322,323 in appserver-io-lab/mage-servlet/src/AppserverIo/Lab/MageServlet/MageServlet.php.

Now I'm running into segfaults in line 385 (ob_start). For debugging proposes I commented this line, but now line 385(\Mage::run()) results in segfault.

I'm using the latest docker container from DavidFeller/docker-appserver, which I updated with composer so it resulted in appserver version 1.0.1. appserver-io-lab/mage-servlet ist the latest available on github.

Is this servlet still up to date? Or are there alternatives.

Not sure if this is an issue with appserver-io-lab/mage-servlet or appserver.io in general.

**Comment by wagnert** [comment]
Hi, sorry for answering late. The MageServlet was an experimental approach, we didn't finalized because of the architectural limitations of Magento 1 that compensates all benefits of a servlet engine.

Actually we recommend using the FastCgi module of the webserver to run Magento via PHP-FPM.
