### ISSUE TITLE
How to achieve a multithreaded use of appserver-io/server 

### ISSUE THREAD

**Issue by chrisdlangton** [appserver-io/appserver#1032]
As the title suggests, i'd like to know how to achieve a multithreaded use of appserver-io/server because the github repo description and README.md claims ~"A multithreaded server daemon framework".

All i can achieve is a single thread with multiple processes, and digging through the source code i can see that it is in fact process forking on the same thread.

> I'm pretty sure PHP cannot achieve "A multithreaded server daemon framework" at all actually, would like to learn how i might be able to do that if you can help me use your project to do what it claims. 

Thankyou

**Comment by smolinari** [comment]
Hi Chris,

The appserverio/server repo is only a small part of the whole appserver system. 

To get all of appserver to work, it needs to be installed. 

http://appserver.io/get-started/documentation/1.1/installation.html

Once you've successfully installed appserver, it offers you basically a finished framework for creating web applications, based on threading (using [pthreads](http://php.net/manual/en/book.pthreads.php)), which means PHP's shared nothing architecture is no longer the case. You can create servlets, beans and other memory persisted (threaded) objects, which aren't destroyed after each request. 

See the docs for more info: http://appserver.io/get-started/documentation/1.1.html

Scott
