### ISSUE TITLE
appserver-io-lab/symfony-wrapper not working for me

### ISSUE THREAD

**Issue by aberfeldy** [appserver-io/appserver#1057]
Hey,
I'm currently evaluating appserver.io for my team to use it with symfony and I liked the fact, that you provide a wrapper with demo bundle to test. But I'm not able to make it work, the ant-tasks are running fine everything looks wonderful, but the only thing I get is a 404 error. screen: https://puu.sh/vJwjA/0fdbdf66a4.png
tried to restart, to rebuild and to find something in the docs, trying to deploy it via a phar b ymyself, but I'm not able to get it to work. is there anything I am missing after the build task (besides restarting app-server)?

**Comment by wick-ed** [comment]
Hi there @aberfeldy 

what version of appserver are you using? We haven't updated the wrapper for quite some time (hence the "Labs" organisation). Will have to evaluate this.

Regards, Bernhard

**Comment by aberfeldy** [comment]
It was installed from the wheezy deb's via apt-get so I assume the latest of the repository. What is strange is, that I can create php and servlets on my own which work quite fine.

**Comment by wick-ed** [comment]
For the same application? So `webapps/symfony`?

**Comment by aberfeldy** [comment]
Oh, no for `webapps/whatever` sorry.
If I create the helloServlet from the tutorials inside the symfony directory I just get `Application symfony has not connected yet`

**Comment by wick-ed** [comment]
Hmm, any logged errors during appserver Startup? Maybe something could not be registered into the naming directory or so? You can find the appserver version within the response header of an HTTP request or at `/opt/appserver/etc/appserver/conf.d/.release-version` by the way.

**Comment by aberfeldy** [comment]
Version: appserver/1.1.3-125 (linux) PHP/5.6.25
log states: (critical): Class 'Symfony\Component\HttpKernel\Kernel' not found []
logs: https://pastebin.com/Raj4kYwE
