### ISSUE TITLE
http://www.appserver.io broken

### ISSUE THREAD

**Issue by softwareishappiness** [appserver-io/appserver#1100]
The web site is completely down. Appears to be a failed installation.

**Comment by wagnert** [comment]
Hello @softwareishappiness We know about that :( Actually we're implementing the german DSGVO regulations. As soon as we've finished that, the page will go back online :)

**Comment by softwareishappiness** [comment]
Thanks. I was hoping that Iron Dragon was releasing...and you guys were updating web site to new version.

**Comment by wick-ed** [comment]
Hi @softwareishappiness site is back up again. :)

We actually did some releases in the meantime (https://github.com/appserver-io/appserver/releases) but mostly bugfixes and small changes e.g. to annotation handling for better usability.

Iron Dragon is still a milestone ahead of us :(

Regards,
Bernhard

**Comment by wick-ed** [comment]
Ah my bad!
Sorry that was a piece of misinformation. Site is still under maintainance due to GDPR issues. :(

**Comment by softwareishappiness** [comment]
GDPR issues resolved yet? It seems like this project is struggling. Website has been down for months. How severe could these issues possibly be???

**Comment by wagnert** [comment]
They're still resolved and i hope we can bring the website back to live again this week :) Sorry for the circumstances, but GDPR is a complicated topic and we don't want to get in trouble german law therefore :(

**Comment by wick-ed** [comment]
Site is back up again. :)
