### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by jamlev** [appserver-io/appserver#1106]
The appserver.io website is down.

**Comment by wick-ed** [comment]
Hi there @jamlev and welcome to Github :)

Thanks for the issue but we intentionally took it down due to the GDPR regulations. :(
Did not have the time to fix all the legal parts yet.

Regards,
Bernhard

**Comment by jamlev** [comment]
I see, Bernhard. Can I be of any help? I had liked the table you featured showing the contrast between appserver.io(PHP) and the Java servlet stack. Do you have a document you can share with similar content?

Thanks,
James

**Comment by wick-ed** [comment]
Hi James,
thanks for the offer, but we just need a legal checkup of the page which is already on the way. :)

A lot of the old site content can be found here: https://github.com/appserver-io/appserver/tree/gh-pages

Is there anything you are currently planing to do with the appserver? We are always interested to hear about any user experiences.
You might also want to check out our gitter chat if so: https://gitter.im/appserver-io/appserver

Best regards,
Bernhard

**Comment by jamlev** [comment]
Thanks for sharing this, Bernhard! We're looking to containerize appserver.io in an offering similar to Platform.sh at best or Heroku at worst but that allows you to assemble a CMS/WCM from PHP frameworks (Lareval, Symfony, CakePHP, etc.) and components (like PECL) following the MDD/MDA approach. This is obviously not for the consumer Web segment whereas the headless CMS customer (medium to larger enterprises) would feel right at home with it. We were working mostly with HHVM to realize this but their roadmap diverged from PHP 7.x too much lately.

Cheers,
James

**Comment by wick-ed** [comment]
Sounds interesting! :)
Where does appserver fill into your plans? Simply as another framework (so you can build appserver.io webapps) or do you want to base your hosted solutions on the appserver infrastructure (if so chosen/or in general)?

Best Regards,
Bernhard

**Comment by wick-ed** [comment]
Puuuhh, sounds like quite a plan! 👍 
I hope you would like to keep in touch as your plan progresses :)
You can always reach us in our gitter chat (also for private chats), here or via email (bw[at]appserver.io) if you have any questions or if we can assist you.

Hope your plans will go well.

Best regards,
Bernhard

**Comment by wick-ed** [comment]
Site is back up again. :)
