### ISSUE TITLE
[appserver-io/website] Server certificate expired on December 1

### ISSUE THREAD

**Issue by emarref** [appserver-io/appserver#1118]
https://appserver.io/

<img width="899" alt="screen shot 2018-12-07 at 2 06 53 pm" src="https://user-images.githubusercontent.com/556594/49621275-659a1500-fa29-11e8-9448-17f964335a38.png">

**Comment by pathmissing** [comment]
Hi @emarref, thank you for reporting this issue, I will look into it right away!

**Comment by pathmissing** [comment]
This issue should now be resolved. Thank you for taking your time and reporting this issue :)
