### ISSUE TITLE
krakjoe/parallel

### ISSUE THREAD

**Issue by fengahan** [appserver-io/appserver#1131]
I believe it would be better if I could replace pthreads with krakjoe/parallel

**Comment by wick-ed** [comment]
Hi there @fengahan ,

thanks for the input!

We already had an, admittedly very brief, look at parallel and think the same.
Also in regards of a possible update to PHP 7 we think we might move away from pthreads.

We just did not have the time to consider all the options and really take action. :(

Regards, Bernhard
