### ISSUE TITLE
Unable to build from source using installation guide 

### ISSUE THREAD

**Issue by a2nt** [appserver-io/appserver#1144]
```
git clone https://github.com/appserver-io/appserver.git
cd ./appserver
➜ ant build
Buildfile: /home/tony/appserver/build.xml

BUILD FAILED
Target "build" does not exist in the project "appserver-io/appserver". 

Total time: 0 seconds

➜ ant deploy 
Buildfile: /home/tony/appserver/build.xml

copy:

BUILD FAILED
/home/tony/appserver/build.xml:95: The following error occurred while executing this line:
Target "prepare" does not exist in the project "appserver-io/appserver". 

Total time: 0 seconds
```

➜ uname -a
Linux hs 4.19.0-5-amd64 #1 SMP Debian 4.19.37-6 (2019-07-18) x86_64 GNU/Linux

**Comment by wagnert** [comment]
@a2nt Did you try a `composer install` before? There should be some libraries that the build process depends on, so `composer install` should solve that. I've i may ask, what is the reason you try to build it by yourself?

**Comment by a2nt** [comment]
hmm looks like there's no way to get it running with the latest debian because it requires PHP < 7.0.0

**Comment by wagnert** [comment]
@a2nt We have a read-to-use Debian build, please look at https://github.com/appserver-io/appserver/releases :-)

**Comment by a2nt** [comment]
@wagnert it will work with old stable debian 8, but it won't work with the latest debian because old one use libcurl3, while the latest has libcurl4 which is required for php 7
So the package has dependencies issues:
  ```
appserver-runtime : Depends: libqdbm14 but it is not going to be installed
                     Depends: libcurl3 but it is not going to be installed
                     Depends: libcloog-ppl0 but it is not installable or
                              libcloog-ppl1 but it is not going to be installed
```

```
> # apt install libcurl3                                                                                       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cmake-data librhash0
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  appimagelauncher cmake curl libcurl4 php-curl php7.3-curl playonlinux
The following NEW packages will be installed:
  libcurl3
0 upgraded, 1 newly installed, 7 to remove and 0 not upgraded.
Need to get 292 kB of archives.
After this operation, 68.2 MB disk space will be freed.
Do you want to continue? [Y/n] ^C
```

**Comment by wick-ed** [comment]
Hi @a2nt 

what Debian version are we talking about? We are currently building on a Debain 9. Debian 10 still gives us issues.

Have a look at our build: https://travis-ci.org/appserver-io-php/runtime/jobs/577862522
Build runs with the following command:
`apt-get update; apt-get install -y ant git; ant dependencies-init; ant local-build -Dbuild.number=local -Dtarget-os.major.version=9 -Dtarget-os.minor.version=9`.

This is [the runtime](https://github.com/appserver-io-php/runtime) though!
Please note that an appserver installation needs the `appserver-dist` AND the `appserver-runtime` package.
The runtime provides a threadsafe compiled PHP-5.6

[The dist package](https://github.com/appserver-io/appserver) is also tested and built for Debian 9. Does need some additional/backport dependencies though. This is most likely what you are seeing.

This should work: https://travis-ci.org/appserver-io/appserver/jobs/620595455
Command currently used `apt-get update && apt-get install -y ant git php && ant dependencies-init -f vendor/appserver-io-dist/debian/build.xml && ant local-build -Dbuild.number=$BUILD_NUMBER -Dtarget-os.major.version=9 -Dtarget-os.minor.version=9 -f vendor/appserver-io-dist/debian/build.xml`

If you followed the documentation then the documentation is outdated. :(

Please try as our travis builds are currently doing or use the provided packages.

If you are talking about Debian 10 then you might have to wait some more days. :(

**Comment by a2nt** [comment]
@wick-ed   I have unstable version of debian (sid) guess need to wait for a while

**Comment by wick-ed** [comment]
Hi @a2nt sid as in "upcoming Debian version"? That might be a liiiiittle to bleeding edge for us. ;)
You might have a look when Buster releases are ready, maybe this will already work for you.

See #1142

I am closing this for now.

**Comment by a2nt** [comment]
@wick-ed thx.

Sid is "unstable version", Buster is "testing/upcoming version". For the testing webserver i prefer sid.

Main issue that it must be built with PHP7 + libcurl4 in this case it will be easy to build it for the latest Debian.
They have dropped support of PHP5 at the future versions
