### ISSUE TITLE
HTTP digest authentication within webserver

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#182]
By now HTTP digest authentication does only work within the `ServletEngine`. This authentication method should be usable within the `WebServer` as well.

UAC:
- HTTP digest authentication MUST be provided by the `WebServer` to the client
- The behavior MUST be configurable within the `appserver.xml`

**Comment by zelgerj** [comment]
fixed in https://github.com/appserver-io/webserver/commit/dd0b8396a7330e7537da57fd81fd971586ba58fe
