### ISSUE TITLE
[appserver-io/appserver] Homebrew installation file

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#184]
UAC:
- The latest appserver build MUST be installable using the `brew install appserver` command

**Comment by michaeldoehler** [comment]
Installation is possible via brew cask (caskroom.io), see merged Pull Request https://github.com/caskroom/homebrew-cask/pull/10121

Cmd: brew cask install appserver

**Comment by wick-ed** [comment]
Closed as of merged PR by @michaeldoehler 

Thanks :)
