### ISSUE TITLE
Timer Service doesn't support seconds as period

### ISSUE THREAD

**Issue by wagnert** [appserver-io/appserver#300]
Actually the Timer Service only supports minutes as smallest period to schedule annotated methods.

UAC:
* The Timer Service should also accept seconds as period to schedule method invokation
* The @Schedule(second=EVERY) attribute should be passed to the timer service

**Comment by wick-ed** [comment]
Closed as of [this commit](https://github.com/wick-ed/appserver/commit/bff55e7f8ebbf6dd7304ee50b599a45a01e247d3).
