### ISSUE TITLE
Provide alternative class loader

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#363]
The current setup purely relies on the `DgClassLoader` for webapp specific directories. If the additional features (AOP, DbC) currently tied into it are not wanted there is no other option than implement a new class loader.

UAC:
- There MUST be another class loader able to simply load from webapp directories 
- This MUST at least work for `WEB-INF`, `META-INF` and `common` directories
- The already existing `SplClassLoader` COULD be used to achieve this UACs

**Comment by wick-ed** [comment]
https://github.com/appserver-io/appserver/pull/364 might give a start on this

**Comment by wagnert** [comment]
Has been fixed with release 1.0.1.
