### ISSUE TITLE
[appserver-io/appserver] Session Handling flexibility

### ISSUE THREAD

**Issue by olysyuk** [appserver-io/appserver#506]
Currently the only session handler type is FileSessionHandler, that is hardcoded inside many parts. Inside StandardGarbageCollector session file removal is present. 

Why not just use http://php.net/manual/en/class.sessionhandlerinterface.php to manage sessions. That will allow database sessions as well.

**Comment by wick-ed** [comment]
Hi @olysyuk , 

looks promising, we will have a look for the next release :+1:

**Comment by wagnert** [comment]
Hi, last but least ;)

We've refactored the session handling with upcoming version 1.1.1. The new release allows the specify a custom session handler in the `META-INF/context.xml` like

```xml
<context>
 <managers>
  ...
   <manager name="SessionManagerInterface" type="AppserverIo\Appserver\ServletEngine\StandardSessionManager" factory="AppserverIo\Appserver\ServletEngine\StandardSessionManagerFactory">
     <sessionHandlers>
       <sessionHandler name="filesystem" type="AppserverIo\Appserver\ServletEngine\Session\FilesystemSessionHandler" factory="AppserverIo\Appserver\ServletEngine\Session\SessionHandlerFactory">
         <!-- params>
           <param name="sessionMarshaller" type="string">AppserverIo\Appserver\ServletEngine\StandardSessionMarshaller</param>
         </params -->
       </sessionHandler>
     </sessionHandlers>
   </manager>
  ...
</context>
```
