### ISSUE TITLE
Wrong Url at http://appserver.io/get-started/tutorials/my-first-webapp.html

### ISSUE THREAD

**Issue by mairl** [appserver-io/appserver#553]
Hi there,

at the page http://appserver.io/get-started/tutorials/my-first-webapp.html#hello-world-script
the part 
**Open the browser at [http://127.0.0.1/myapp/hello.php] and you should get...**
should be 
**Open the browser at [http://localhost:9080/myapp/hello.php] and you should get...***

cheers Ludwig

**Comment by wagnert** [comment]
Hi Ludwig, fixed :) LG

Am 2/15/15 um 11:48 AM schrieb mairl:
>
> Hi there,
>
> at the page 
> http://appserver.io/get-started/tutorials/my-first-webapp.html#hello-world-script
> the part
> *Open the browser at [http://127.0.0.1/myapp/hello.php] and you should 
> get...*
> should be
> *Open the browser at [http://localhost:9080/myapp/hello.php] and you 
> should get...**
>
> cheers Ludwig
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/appserver-io/appserver/issues/553>.
>


-- 

Tim Wagner

Head of Development / Design

Magento Certified Developer Plus

Certified Scrum Master

Telefon +49 8031 2210 55 - 0

Telefax+49 8031 2210 55 - 22

t.wagner@techdivision.com <mailto:info@techdivision.com>

TechDivision GmbH

Spinnereiinsel 3a
83059 Kolbermoor

MAGENTO GOLD PARTNER

TYPO3 Gold Member

Geschäftsführer: Josef Willkommer, Stefan Willkommer
Handelsregister Nr. HRB 17123, Amtsgericht Traunstein
UStID gemäß § 27 a Umsatzsteuergesetz: DE249664276

www.techdivision.com <http://www.techdivision.com> TechDivision
