### ISSUE TITLE
Restart problem

### ISSUE THREAD

**Issue by mairl** [appserver-io/appserver#554]
after following the steps at http://appserver.io/get-started/tutorials/my-first-webapp.html#hello-world-script

http://appserver.io/get-started/tutorials/my-first-webapp.html#hello-world-script
does not work for me, it appears coomand not found

instead sudo /opt/appserver/sbin/appserverctl restart works for me. Though, whats right or wrong

cheers Ludwig

**Comment by wagnert** [comment]
Hi Ludwig, thanks! Fixed :) LG

Am 2/15/15 um 11:59 AM schrieb mairl:
>
> after following the steps at 
> http://appserver.io/get-started/tutorials/my-first-webapp.html#hello-world-script
>
> http://appserver.io/get-started/tutorials/my-first-webapp.html#hello-world-script
> does not work for me, it appears coomand not found
>
> instead sudo /opt/appserver/sbin/appserverctl restart works for me. 
> Though, whats right or wrong
>
> cheers Ludwig
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/appserver-io/appserver/issues/554>.
>


-- 

Tim Wagner

Head of Development / Design

Magento Certified Developer Plus

Certified Scrum Master

Telefon +49 8031 2210 55 - 0

Telefax+49 8031 2210 55 - 22

t.wagner@techdivision.com <mailto:info@techdivision.com>

TechDivision GmbH

Spinnereiinsel 3a
83059 Kolbermoor

MAGENTO GOLD PARTNER

TYPO3 Gold Member

Geschäftsführer: Josef Willkommer, Stefan Willkommer
Handelsregister Nr. HRB 17123, Amtsgericht Traunstein
UStID gemäß § 27 a Umsatzsteuergesetz: DE249664276

www.techdivision.com <http://www.techdivision.com> TechDivision
