### ISSUE TITLE
Problems to insert a Service

### ISSUE THREAD

**Issue by mairl** [appserver-io/appserver#561]
Hi Tim,

i have tryed to follow the example **Using Services** on 
http://appserver.io/get-started/tutorials/my-first-webapp.html
as soon i add **$this->helloService->getHelloMessage()** to **$servletResponse->appendBodyStream**

i receive following error message:
exception 'AppserverIo\Psr\Naming\NamingException' with message 'Cant't resolve HelloService in naming directory php:' in /opt/appserver/src/AppserverIo/Appserver/Naming/BindingTrait.php:176 Stack trace: #0 /opt/appserver/src/AppserverIo/Appserver/Naming/BindingTrait.php(172): AppserverIo\Appserver\Naming\NamingDirectory->search('HelloService', Array) #1 /opt/appserver/vendor/appserver-io/rmi/src/AppserverIo/RemoteMethodInvocation/LocalContextConnection.php(118): AppserverIo\Appserver\Application\Application->search('HelloService', Array) #2 /opt/appserver/vendor/appserver-io/rmi/src/AppserverIo.......

cheers Ludwig

**Comment by wick-ed** [comment]
Cannot be reproduced

**Comment by mroswald** [comment]
Same problem here, is this related to windows hosts?

**Comment by mroswald** [comment]
Ok, got it! Please be aware, that the Service should be in META-INF directory structure, the servlet in WEB-INF. moving the service class file solved the issue

**Comment by wick-ed** [comment]
Hi there,

yes that's true. We do assume a certain structure within appserver.io webapps.
You might have a read [here](http://appserver.io/get-started/documentation/webapps.html).

Regards,
Bernhard
