### ISSUE TITLE
Errorcode "61 unassigned" after restarting OS

### ISSUE THREAD

**Issue by ahoffmeyer** [appserver-io/appserver#587]
Hi there!
I noticed some curious effects: After restarting the OS no PHP-files can be opened in the browser directly. Changing file permissions with server.php -s dev/prod (or even manually) does not have any effects. Reinstalling appserver gives access to PHP-files again. 
Error is thrown in line 156 of:
/opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/Modules/FastCgiModule.php

**Comment by tobemedia** [comment]
I've had a similar problem also causing unassigned errors. I my case it was a problem with the configured IP addresses.

**Comment by ahoffmeyer** [comment]
How did you solved this? Setting IP addresses to 0.0.0.0?

**Comment by tobemedia** [comment]
Yes, that worked for me. Don't forget to restart appserver. I'm not shure but I believe it was a 111 in my case.

**Comment by ahoffmeyer** [comment]
I gave it a try, but I still get the error:

exception 'AppserverIo\Server\Exceptions\ModuleException' with message 'Connection refused' in /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/Modules/FastCgiModule.php:156
Stack trace:
#0 /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/ConnectionHandlers/HttpConnectionHandler.php(498): AppserverIo\WebServer\Modules\FastCgiModule->process(Object(AppserverIo\Http\HttpRequest), Object(AppserverIo\Http\HttpResponse), Object(AppserverIo\Server\Contexts\RequestContext), 2)
#1 /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/ConnectionHandlers/HttpConnectionHandler.php(425): AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler->processModules(2)
#2 /opt/appserver/vendor/appserver-io/server/src/AppserverIo/Server/Workers/ThreadWorker.php(256): AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler->handle(Object(AppserverIo\Server\Sockets\StreamSocket), Object(AppserverIo\Server\Workers\ThreadWorker))
#3 /opt/appserver/vendor/appserver-io/server/src/AppserverIo/Server/Workers/ThreadWorker.php(183): AppserverIo\Server\Workers\ThreadWorker->work()
#4 [internal function]: AppserverIo\Server\Workers\ThreadWorker->run()
#5 {main}

**Comment by zelgerj** [comment]
Hi guys, thanks for that feedback. I'll have a look at it...

**Comment by zelgerj** [comment]
@ahoffmeyer: I'am not able to reproduce the problem you got. Can you give us more information about every single step you made to get the error.

Have you also checked that the php-fpm daemon is up and running?
Please try to do a restart of it and recheck if that problem still exists

```bash
sudo /opt/appserver/sbin/appserver-php5-fpmctl restart
```

**Comment by ahoffmeyer** [comment]
You made my day :) that was the problem. Thanks a lot !!!

**Comment by zelgerj** [comment]
You're welcome ;)
