### ISSUE TITLE
[appserver-io/appserver] Multithreading in Windows

### ISSUE THREAD

**Issue by ndamofli** [appserver-io/appserver#653]
Hi there, I installed the windows version of appserver and i have a problem with multithreading. 
I have a simple php script that runs an exec command and returns the output.
I am trying to run this script multiple times concurrently but my requests are processed one by one (serial). 
I am using another (apache) server to invoke the requests to appserver via multi-curl.

**Comment by zelgerj** [comment]
Hi, could you paste your script here? it's will help a lot to understand whats intended to do. Cheers.

**Comment by ndamofli** [comment]
I am using phantomjs.exe (a headless browser) to create screenshots of websites.
My intention is to make multiple parallel queries to appserver's webserver like the following:

http://localhost:9080/phantom/phantom_bp.php?url=$url

The script phantom_bp.php contains:
$command = "phantomjs.exe phantom.js $url";
function exec_alt($cmd, $counter){
    $return = exec($cmd, $output);
    if (!$output) {
		$return = "NOPHANTOM";
	}
    return $return;
}

I use multi-curl to invoke multiple requests from another script on another webserver.

**Comment by zelgerj** [comment]
Ok thanks for sharing you script. Is that script called from browser or another Webserver using another script which uses multicurl?... sorry for that questions... but i still can not follow you... could you visualize your request chain like.

1. Browser requests http://...
2. Triggered script via apache and mod-php uses multi_curl and requests http://...
3. Triggered script via appservers webserver requests phantomjs.exe

**Comment by ndamofli** [comment]
This script is called from chrome browser from another webserver (apache @ localhost:80) and it uses multicurl. 
So the chain is as follows:
1. Browser (chrome) requests multi_update.php from apache server @ port 80
2. apache php script makes multiple requests to appserver (@ port 9080) via multi curl
3. php script in appserver requests phantomjs.exe
Thank you so much for your time and effort

**Comment by zelgerj** [comment]
Ok what if you call the appserver script (@port 9080) directly from the browser. Does that work concurrently?

**Comment by ndamofli** [comment]
No it doesn't. I tried opening multiple chrome windows and they don't work concurrently

**Comment by zelgerj** [comment]
I guess `exec` under windows causes the process to block while the execution is in progress. You could try to replace the `exec` with `error_log('simulate phantomjs to be executed');sleep(1);` to see if it is still not concurrently.

**Comment by ndamofli** [comment]
Unfortunately i still have serial output. I opened 5 windows with sleep time 5secs and the request were processed one after another (not parallel)

**Comment by zelgerj** [comment]
Ok i'll check that on my windowz machine...

**Comment by ndamofli** [comment]
thank you zelgerj

**Comment by zelgerj** [comment]
hm sorry but i can not reproduce your problem. Parallel requests on a script with sleep(5) are processed all concurrently... some special on your configuration or windows system itself?!

**Comment by ndamofli** [comment]
well i didn't make any changes to the default configuration of appserver, and i'm only using a simple wamp server (for apache, php mysql) on a windows 7 64bit hexacore i7. bummer.

**Comment by ndamofli** [comment]
could u please send me a link of your installation.? maybe i have a wrong version of appserver (i downloaded it today from appserver's homepage)

**Comment by zelgerj** [comment]
The link should be ok... I'll create a test for that scenario, that checks if it is non-concurrent. I'll get back on you if it ready...

**Comment by ndamofli** [comment]
Thank you very much Zelgerj.. Just to let you know, i installed appserver to another machine (win7 32 bit this time) and i had the same problem (tried the multiple windows & sleep script).

**Comment by zelgerj** [comment]
@ndamofli: Finally i'am not able to reproduce the problem. Could you setup a virtual machine and gimme access to it, so i can reproduce and debug the problem?

**Comment by wick-ed** [comment]
Hi @ndamofli ,

can you give us an update on this issue? We were not able to reproduce it here and would like to close it if the problem does not exist anymore.

**Comment by wick-ed** [comment]
Closed as not reproducable
