### ISSUE TITLE
[appserver-*/*] minimize context inheritance in between threads

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#678]
Currently a new thread context will inherit everything known to its parent context. This speed ups several processes but produces a huge overhead.

UAC:
* Inheritance MUST be limited to the possible minimum
* Workflow and performance MUST  NOT be influenced in a significant way (max. -5% rps)

**Comment by zelgerj** [comment]
fixed in https://github.com/appserver-io/appserver/pull/816
