### ISSUE TITLE
Install error on debian

### ISSUE THREAD

**Issue by simkea** [appserver-io/appserver#713]
$>dpkg -i appserver-dist_1.0.2-57_amd64.deb

Fatal error: Call to undefined function AppserverIo\Appserver\Core\appserver_get_envs() in /opt/appserver/server.php on line 46
dpkg:  Fehler beim Bearbeiten von appserver-dist (--install)

**Comment by wick-ed** [comment]
Hi @simkea ,

looks like there was a problem with your runtime.

How was the system set up prior to this installation attempt?
Was there an appserver installation before? 
What version of the appserver runtime do you have installed?

Regards,

Bernhard

**Comment by simkea** [comment]
o.k.
i have now purged & autoremoved appserver-runtime and appserver-dist ... aware individually!
now: Setup for mode 'install' done successfully!

thx

**Comment by wick-ed** [comment]
Hi @simkea ,

so everything works well now?
What has been the problem?
Did you install an older runtime before?

Regards, Bernhard

**Comment by simkea** [comment]
two days ago i installed appserver about your instruction. Server runs perfekt.
Yesterday I installed node.js then, phantomjs and log.io .
Then I got the error message 500 from the appserver. I was very confused.
Now I have everything cleaned completely. Newly Installed. Now the server is working again.
i don´t know what was the problem...
br Henry

**Comment by wick-ed** [comment]
I can't think of a scenario where this behavior is caused solely by installing third party products.
Normally this would occur if trying to run the appserver with a common PHP binary missing some extensions we need.

I will close the issue as things worked out but if you might think of something that could have caused the issue we would be glad to hear about it.

Regards, Bernhard
