### ISSUE TITLE
Can't override init() method

### ISSUE THREAD

**Issue by hanschrome** [appserver-io/appserver#722]
I can't override the method init(); when I did that and restart the service(windows) not reply my http requests. I have to delete this code and restart again the service for it works. 
Does not work with the sample code of the website. I tried to use web.xml, but if I use it, don't found my servlets. ServletNotFoundException bla, bla, bla.

    <servlet>
        <description>Login</description>
        <display-name>Login</display-name>
        <servlet-name>loginServlet</servlet-name>
        <servlet-class>\vendor\test\LoginServlet</servlet-class>
    </servlet>

    <servlet-mapping>
        <servlet-name>loginServlet</servlet-name>
        <url-pattern>/login.do</url-pattern>
    </servlet-mapping>

I see in the example the same relative url, but doesn't work. I don't know what is wrong. If i use annotation it works, but init() method not.

**Comment by wagnert** [comment]
@hanschrome Please post the code of your Servlet implementation here?

**Comment by wagnert** [comment]
@hanschrome Ok, so i understand your environment :) Could you please post the error message/stack trace when you try to override the init() method.

**Comment by hanschrome** [comment]
@wagnert  I haven't got any error, simply I haven't got http service, It is the problem. I don't know anything about it, and being a service I haven't got any console for see anything. For get the service again, I have to delete init() and restart-service appserver.  Is very tired restart the service for each change when are developing the program.

**Comment by hanschrome** [comment]
Now works, I deleted the folder project, created new folder, copy-paste the files, change paths in files and it works, nothing has sense in this life.

Thank you for all.

**Comment by wagnert** [comment]
@hanschrome You're welcome, hope that you don't face problems anymore :)
