### ISSUE TITLE
Can't Debug with appserver.io

### ISSUE THREAD

**Issue by hanschrome** [appserver-io/appserver#730]
Hello,

I need know how I can debug my web application like I can in xamp, wamp, lamp... with netbeans, eclipse... I am using Windows with netbeans, I need test code and I didn't find anything about debug line per line: xdebug. When I active xdebug in my IDE all the time is waiting for connection. Is there any way ?

Thanks.

**Comment by wick-ed** [comment]
Hi @hanschrome ,

debugging within the appserver is sadly not that easy.
xDebug is not able to cope with a multithreaded environment (nor is any other debuggin tool afaik).

If you want to use xDebug for debugging you have to test your application in a single-threaded environment e.g. during unit or functional testing.
Within a running appserver debugging has to be done using GDB and var_export/error_log dumps.

We are hoping for https://github.com/krakjoe/phpdbg to kick in in the near future.

Regards,
Bernhard
