### ISSUE TITLE
Old documentation

### ISSUE THREAD

**Issue by sydekumf** [appserver-io/appserver#736]
The web-app node in the web.xml example on http://appserver.io/get-started/documentation/servlet-engine.html#optional-xml-configuration is not correct. It should be  `<web-app xmlns="http://www.appserver.io/appserver">`.

**Comment by wick-ed** [comment]
Done as of [this commit](https://github.com/appserver-io/appserver/commit/e4fc12e1fa6ea39fdfbdddcaeb5891451c3e8659).

**Comment by sydekumf** [comment]
Please also fix http://appserver.io/get-started/documentation/webserver.html#authentications :-) Seems like the following would be correct (from example webapp):

    <security>
        <url-pattern>/index.do/basicAuthentication*</url-pattern>
        <auth>
            <auth-type>Basic</auth-type>
            <realm>test</realm>
            <adapter-type>htpasswd</adapter-type>
            <options>
                <file>WEB-INF/htpasswd</file>
            </options>
        </auth>
    </security>

**Comment by wagnert** [comment]
Hi @sydekumf, i think you mixed up webserver and servlet engine access configuration, is that possible?
