### ISSUE TITLE
[appserver-io/appserver] MySQL datasources permission denied

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#770]
There seems to be a problem when using the datasource mechanism in combination with a MySQL database.

**Comment by a-winter** [comment]
My datasource configuration and using the latest webserver.io 1.0.4 and runtime 1.0.5
```
<?xml version="1.0" encoding="UTF-8"?>
<datasources xmlns="http://www.appserver.io/appserver">
    <datasource name="8select.database">
        <database>
            <driver>pdo_mysql</driver>
            <user>user</user>
            <password>password</password>
            <databaseName>database</databaseName>
	    <path></path>
        </database>
    </datasource>
</datasources>
```

Error message is
```
{"error":{"message":"An exception occured in driver: SQLSTATE[HY000] [2002] Permission denied"}}
```

**Comment by hhoechtl** [comment]
Because the merge is done, this ticket can be closed as the "Permission denied" resulted from a missing dbname connection parameter

**Comment by wick-ed** [comment]
Can any of you ( @hhoechtl , @a-winter ) verify this with a test?

**Comment by hhoechtl** [comment]
I already verified this with the example webapp. @a-winter will probably sometime today when he tries do provision his doctrine models.

**Comment by wick-ed** [comment]
Great, thanks :)
