### ISSUE TITLE
[documentation] The contribution section is outdated

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#772]
The [contribution section of our homepage](http://appserver.io/community/contributing.html) is kind of outdated and does not contain most useful information.

UAC:
* The page MUST contain mentions of the Gitter chat, Issue tracker and the Github repository
* The page MUST NOT contain old or misleading information (looking at you stackoverflow!)
* The page SHOULD make a statement about expected coding standards and levels of quality
* These guidelines COULD be mentioned in an `.CONTRIBUTING` file enclosed in project repos

**Comment by smolinari** [comment]
I noticed you mention opening a forum. Will you still be doing this? If yes, I can be of assistance, if you'd like. I've worked with forum software (vbulletin-germany.com) for the last 14 years and can help with putting a forum together for you. I wouldn't suggest using vBulletin, but rather XenForo. Just let me know if you are interested. I'd be glad to help.

Scott

**Comment by wick-ed** [comment]
Hi Scott :)

thank you very much for the offer.
A forum will most likely only be part of our paid support infrastructure. Currently we would like to rely on [stackoverflow](http://stackoverflow.com/) for Q&A and discussions.
So no forum for now but thanks again. :)

**Comment by smolinari** [comment]
Well, when you are ready, you know where to find me. :)

Scott
