### ISSUE TITLE
[appserver-io/appserver] Installation on Ubuntu Gnome 15.04 not possible

### ISSUE THREAD

**Issue by wagnert** [appserver-io/appserver#798]
I tried installing appserver.io on Ubuntu Gnome 15.04 and met an obstacle that keeps me from installing the server.

First I tried the repository approach as stated at http://appserver.io/get-started/downloads.html#debian. I then got the message:
"The following packages have unmet dependencies:
appserver-runtime : Depending on: libdb4.8 which is a virtual package. or libdb5.1 which is a virtual package."

After this I tried downloading and installing "appserver-runtime_1.09.5-48_amd64.deb", got the same result with missing dependency libdb4.8 / libdb5.1

I have also searched online for solution to this, no luck. I did however notice that other people are experiencing same issue. Are you aware of this, do you have a solution?

I hope to hear from you, if you need any additional information please let me know.

**Comment by tristanlins** [comment]
Same here, under ubuntu 15.04 server and kubuntu 15.04:

-----

```
# apt-get install appserver-dist
...
The following packages have unmet dependencies:
 appserver-dist : Depends: appserver-runtime but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

-----

```
apt-get install appserver-dist appserver-runtime
...
The following packages have unmet dependencies:
 appserver-runtime : Depends: libdb4.8 but it is not installable or
                              libdb5.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

-----

```
apt-get install appserver-dist appserver-runtime libdb4.8
...
E: Package 'libdb4.8' has no installation candidate
```

-----

```
apt-get install appserver-dist appserver-runtime libdb5.1
...
Package libdb5.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  db5.1-util:i386 db5.1-util

E: Package 'libdb5.1' has no installation candidate
```

-----

```
apt-get install appserver-dist appserver-runtime db5.1-util
...
The following packages have unmet dependencies:
 appserver-runtime : Depends: libdb4.8 but it is not installable or
                              libdb5.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by wick-ed** [comment]
There where dependency problems with `libdb` and `libjpeg` when looking at Debian builds. This problem should be solved with [this commit](https://github.com/wick-ed/debian/commit/5883501cc1cf43eb205213e2d26780d5b3ec992d) which will make upcoming builds available on Ubuntu again.

**Comment by jcmarchi** [comment]
Hello guys.

This is an old thread, but looks like even today (2017 already) no one has resolved the Ubuntu installation issues, neither the required libraries got included in Ubuntu Distro (well, they moved to the libicu55, which is not recognized by AppServer).

In the attempt to help others, here below a quick set of instructions to install AppServer in Ubuntu (16.10, maybe work for other versions as well).

There are two successful attempts I would like to share. The first one, obviously, will be the best one if it works for you. The second attempt will work when the "appserver.service" fails to start (as it cannot be found in certain scenarios for some reason). You can try one, then try the second one if the first one fail (or go to the second one direct if you want). Have fun. :)

## **BEST INSTALLATION METHOD:**

Download and install the .deb package "**libicu52_52.1-8_amd64.deb**" from
https://launchpad.net/ubuntu/wily/amd64/libicu52/52.1-8

Download and install the .deb package "**libicu48_4.8.1.1-3_amd64.deb**" from
https://launchpad.net/ubuntu/precise/amd64/libicu48/4.8.1.1-3

Then install the AppServer using:
```
sudo su
echo "deb http://deb.appserver.io/ wheezy main" > /etc/apt/sources.list.d/appserver.list
wget http://deb.appserver.io/appserver.gpg -O - | apt-key add -
apt update
apt upgrade
apt install appserver-runtime appserver-dist
```

## ANOTHER INSTALLATION METHOD (brute force):
_you may decide to use this method, which will most likely work for all cases. Also, if the previous method fails, don't worry. You won't need to uninstall anything. Simply start over using this method instead (you may want to jump these first steps and go directly to the point when you will have to download and install the Debian 7 Wheezy 64-bit packages from the appserver.io site)._

Download and install the .deb package "**libicu52_52.1-8_amd64.deb**" from
https://launchpad.net/ubuntu/wily/amd64/libicu52/52.1-8

Download and install the .deb package "**libicu48_4.8.1.1-3_amd64.deb**" from
https://launchpad.net/ubuntu/precise/amd64/libicu48/4.8.1.1-3

Then install the AppServer base:
```
sudo su
echo "deb http://deb.appserver.io/ wheezy main" > /etc/apt/sources.list.d/appserver.list
wget http://deb.appserver.io/appserver.gpg -O - | apt-key add -
apt update
apt upgrade
```

In this attempt, we will use the _Debian 7 Wheezy 64-bit_ packages to force-install the AppServer. Those can be found at: http://appserver.io/get-started/downloads.html#Debian

download and install the "**appserver-runtime_1.1.6-97-deb7_amd64.deb**".
download and install the "**appserver-dist_1.1.3-125-deb7_amd64.deb**".                            

Both packages should successfully install, but the AppServer will still fail to start.
Yet as "sudo", simply repeat the installation process via "apt" to fix it:

`apt install appserver-runtime appserver-dist`

All done!

I hope it helps.

**Comment by wagnert** [comment]
@jcmarchi Thanks for that awesome work :) We'll update the packages as soon as possible, so it shouldn't be necessary to install additional libraries before installing appserver. But till then, i think this will help a lot :)
