### ISSUE TITLE
[appserver-io/appserver] URL Routes according to REST defacto standard

### ISSUE THREAD

**Issue by hhoechtl** [appserver-io/appserver#840]
It would be great, if it's possible to have URLs like /something/action.do/:id/update/:address

Some libraries already use this format of REST endpoints:
http://www.restapitutorial.com/lessons/httpmethods.html
https://docs.angularjs.org/api/ngResource/service/$resource

**Comment by smolinari** [comment]
Wouldn't this be similar to doing something like Routlt? Maybe RoutRest? :smile: 

Theoretically, it would be better, if the REST routes shouldn't have .do file extensions in them either. 

Scott

**Comment by akleiber** [comment]
+1 for this

As mentioned by @smolinari we should get rid of the `.do` suffix.
Some example resources would be:

```
/books
/books/123
/books/123/authors
/books/123/authors/1
```

I am mentioning filtering and pagination although this would be another issue

```
/books?filter.id=123&filter.release=2010&limit=10&offset=30&sort=+id&sort=-author.name
```

Example implementations:

* Java Spring MVC `@RequestMapping` http://www.journaldev.com/3358/spring-mvc-requestmapping-annotation-example-with-controller-methods-headers-params-requestparam-pathvariable
* PHP Silex Routes http://silex.sensiolabs.org/doc/usage.html#dynamic-routing

**Comment by wick-ed** [comment]
Hi @akleiber ,

thanks for the examples. :)
We too discussed this to be an enormously useful feature. Sadly this has to come second to other issues. :(
Will come to that in the future.

@smolinari I would rather go with `Restlt` :D

The `.do` extension can be hidden using rewrites but is currently needed to determine the backend used for processing (servlet engine vs. FastCGI vs. PC vs. ...).

Regards,

Bernhard

**Comment by smolinari** [comment]
Restlt sound good! Maybe Tim can rename the project he is working on. :smile: 

https://github.com/wagnert/api

Scott

**Comment by wick-ed** [comment]
:smile:

**Comment by wagnert** [comment]
Issue moved to [appserver-io/routlt #38](https://github.com/appserver-io/routlt/issues/38) via [**ZenHub**](https://www.zenhub.com/)
