### ISSUE TITLE
[appserver-io/doppelgaenger] Cannot use Traits

### ISSUE THREAD

**Issue by hhoechtl** [appserver-io/appserver#842]
I have a simple trait serving a protected method. Runtime 1.1.0 beta1, Appserver 1.1.0 Beta 3
The trait is not even in use, but I get the following error:

    PHP Fatal error:  Call to protected method AppserverIo\Doppelgaenger\Parser\TraitParser::getAttributes() from context 'AppserverIo\Doppelgaenger\Parser\TraitParser' in /Users/jhoechtl/workspace/appserver/appserver/vendor/appserver-io/doppelgaenger/src/Parser/TraitParser.php on line 141

I solved the error by setting the visibility of the method getAttributes in the PropertyParserTrait of Doppelgaenger to public.

**Comment by wick-ed** [comment]
Solved with [this release](https://github.com/appserver-io/doppelgaenger/releases/tag/1.4.2)
