### ISSUE TITLE
[appserver-io/appserver] Default server reachability should be all IPs

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#844]
Currently any server started with default configuration is only reachable locally (`127.0.0.1`). This must be changed.

UAC:
* Servers serving content MUST be reachable per default
* Servers SHOULD use the 0.0.0.0 mask

**Comment by smolinari** [comment]
Oh gee. Now I have to change my article to mention the IP binding is being changed in version 1.1.0. LOL!

Scott

**Comment by wick-ed** [comment]
Hi Scott,

yes, we had to make this change, there were too much people asking why the server is not reachable remotely.

**Comment by smolinari** [comment]
Ok. Then I might only need to change the version number in the article. I still have two or three articles to write.:-)

Scott

**Comment by wick-ed** [comment]
Hehe, there is no rest when working with the appserver. ;)
