### ISSUE TITLE
[appserver-io/appserver] Memory Leaks in Session Beans

### ISSUE THREAD

**Issue by wagnert** [appserver-io/appserver#859]
When using Doctrine to import a huge amount of rows from a database into Elasticsearch using a Session Bean, for example, memory will not be freed as expected. Using [gc_collect_cycles](http://php.net/manual/de/function.gc-collect-cycles.php) seems to keep memory consumption on a continuous level.

Invokcation of `gc_collect_cycles` after each call to a Session Bean could probably a solution.

**Comment by wick-ed** [comment]
First tests with `memory_get_usage()` did not show abnormal memory use within any bean type.

**Comment by wick-ed** [comment]
Fixed with [this release](https://github.com/appserver-io/appserver/releases/tag/1.1.1-beta10)
