### ISSUE TITLE
Multiple virtual host configuration files

### ISSUE THREAD

**Issue by 2case** [appserver-io/appserver#895]
Currently it seems not possible to setup multiple virtual hosts configuration files. They will overwrite each other. Handling all virtual hosts configurations in one large file is not very organized.

I would also like something like ```<xi:include href="conf.d/*"/>``` to load all files in that directory.

**Comment by wick-ed** [comment]
Hi there @2case ,

you should be able to use several virtual hosts config files using a slightly different structure within the XML file.
Something along the lines of this:

```xml
<virtualHosts>
     <!-- include of virtual host configurations -->
     <xi:include href="conf.d/virtual-hosts-1.xml"/>
     <xi:include href="conf.d/virtual-hosts-2.xml"/>
     <!-- .... -->
</virtualHosts>
```

With your virtual host configurations only wrapped in a single `virtualHost` node each.

This might get a little clunky as the wildcard based syntax you would like is not supported by `XInclude` mechanisms.
We would love to see something like that as well.

Regards,

Bernhard

**Comment by smolinari** [comment]
This is good to know! (and something else to add to the docs.) :smile: 

Scott

**Comment by 2case** [comment]
I tried that, but the XML Parser did not allowed the xi:include inside the virtualHosts node!

**Comment by wick-ed** [comment]
Hehe ^^
One of the reasons we are using XML for configuration is the manifold of tools and functions it offers.
You can use any of these with the appserver configuration so XInclude should work like it does in other XML files.

@2case , oh! Might be we restrict the type of the child nodes, I will check the schema. Sorry about that.

**Comment by 2case** [comment]
Hm missing the like button on your post... ah found the :+1:

**Comment by wick-ed** [comment]
Works as explained above in a local test with appserver version 1.1.0 "Iron Knight".

Example for appserver config in `appserver.xml`.

```xml
<!-- include of virtual host configurations -->
<virtualHosts>
    <xi:include href="conf.d/virtual-hosts-1.xml"/>
    <xi:include href="conf.d/virtual-hosts-2.xml"/>
</virtualHosts>
```

Example for virtual host configs.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<virtualHost xmlns="http://www.appserver.io/appserver" name="test.dev">
    <!-- -->
</virtualHost>
```

Have a try with the current version. :)

**Comment by smolinari** [comment]
If I have some time, I'll play with this. I already have several virtual hosts set up for testing different things. Since I've started working with appserver, I haven't used any other server stack. LOL! The only thing missing is PHP debugging facilities. Once they are in, I'll be server in heaven! :smiley: 

Scott
