### ISSUE TITLE
Cant enable intl extension

### ISSUE THREAD

**Issue by armababy** [appserver-io/appserver#896]
Hey,

When trying to enable intl extension php never picks it up.
Been trying on two fresh systems.

Server: Ubuntu 14.02 LTS
appserver.io: appserver/1.0.6-37 (linux) PHP/5.5.25

With running appserver, steps to reproduce (running as root):
0. Check for extension ``/opt/appserver/bin/php --ri intl``
1. Enable intl extension ``nano /opt/appserver/etc/conf.d/intl.ini``, change ``;extension = intl.so`` to ``extension = intl.so``.
2. Restart php-fpm service ``service appserver-php5-fpm restart``.
3. Check for extension ``/opt/appserver/bin/php --ri intl``

Expected output:
Something like this
```
intl

Internationalization support => enabled
version => 1.1.0
ICU version => 52.1
ICU Data version => 52.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

Output receiving:
```
Extension 'intl' not present.
```

Edit: Might add that i tried to disable and enable other extensions like gd and xsl. Sure they were disabled and i could re-enable them back, using same process as described for intl.

Thanks.

**Comment by smolinari** [comment]
FYI, my Debian Wheezy VM, latest version, works as expected. 

Scott

**Comment by DavidFeller** [comment]
Hi, 

I'm running several Ubuntu 14.04.x servers with activated intl inside docker. To activate intl I used the following steps:

1. install Ubuntu's ```libicu-dev``` (libicu52 ?!)
2. reinstall the intl extension using pecl
```sudo /opt/appserver/bin/pecl install intl```
3. ```sudo service restart appserver-php5-fpm```

You can also find these steps in my Dockerfile (https://github.com/DavidFeller/docker-appserver-magento/blob/master/Dockerfile). ;-)

David

**Comment by armababy** [comment]
@DavidFeller thank you for docker file, helped a lot.

reinstaled intl using pecl, had to install ``libicu-dev build-essential autoconf`` for all this to work.
in the end now i have working intl 3.0 :)

Thanks

**Comment by DavidFeller** [comment]
@armababy happy I could help :)
