### ISSUE TITLE
[appserver-io/appserver] Leading slash in absolute certPath ignored

### ISSUE THREAD

**Issue by DavidFeller** [appserver-io/appserver#900]
I tried to set the certPath to an absolute location e.g. ```<param name="certPath" type="string">/etc/ssl/mycert.pem</param>```, but it seems that the leading slash is ignored. If I copy the same .pem file to ```/opt/appserver/etc/ssl/mycert.pem```, it works as excepted. 

To double-check I installed a clean Ubuntu 14.04.3 with appserver 1.0.6-37 using the debian wheezy packages and used the ```server.pem``` file which is shipped with appserver-dist.

**Comment by wagnert** [comment]
Has been fixed with server version 2.0.1 which has been part of appserver.io version >= 1.1.0.
