### ISSUE TITLE
[appserver-io/appserver] Allow re-attaching of SFSBs to current user sessions

### ISSUE THREAD

**Issue by wick-ed** [appserver-io/appserver#901]
SFSBs are mapped to known user sessions. Using DI in a webapp simplifies the usage of SFSBs and other beans. Problem is, that if one does something involving changes to the user session within a webapp, the SFSB previously injected does not match that changed session. Considering a login where a new session is started, this will result in "loss" of all data stored in the SFSB currently used as it is bound to any previously present session. An (active) re-attaching of currently present SFSB instances to the current session can help the bean manager to keep track of session changes without loss of beans.

UAC:
- SFSB-to-session mapping MUST be updateable/updated on session changes

**Comment by smolinari** [comment]
Thinking "immutable objects", how about expecting the app to just build a new SFSB and void/ delete the old one? Not sure if that makes sense, but it seems the kind of place to do it.

http://blog.joefallon.net/2015/08/immutable-objects-in-php/

Scott

**Comment by smolinari** [comment]
Out of curiosity, but what was changed in the code?

Scott

**Comment by wagnert** [comment]
@smolinari It's not too much, but efficient ;)

**Comment by smolinari** [comment]
Simple and efficient are almost in all cases the best solutions! :smile: 

Scott
