### ISSUE TITLE
[appserver-io/appserver-io-dist/debian] libjpeg.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by waja** [appserver-io/appserver#910]
Looking into https://github.com/appserver-io-dist/debian/blob/master/src/generic/runtime/DEBIAN/control the dependencies seems to be solved when installing ```libjpeg8``` or ```libjpeg62-turbo```. Anyway, installing the (Wheezy) package on Debian Jessie (where ```libjpeg8``` is not available) I get the following error:

```
Setting up appserver-dist (1.0.6-37) ...
/opt/appserver/bin/php: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
dpkg: error processing package appserver-dist (--configure):
 subprocess installed post-installation script returned error exit status 127
Processing triggers for libc-bin (2.19-18+deb8u1) ...
Errors were encountered while processing:
 appserver-dist
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

It looks like ```/opt/appserver/bin/php``` is dymanical linked against ```libjpeg.so.8``` which is provided by ```libjpeg8```.

**Comment by wagnert** [comment]
Hi, actually we only have appserver 1.1.0 beta packages compiled for Debian Jessie. Have a look at http://builds.appserver.io and try the latest beta7 packages.

**Comment by waja** [comment]
I'm using the wheezy package in my Jessie docker image like you do in https://github.com/appserver-io-dist/docker/blob/master/appserver/1.0.6/Dockerfile#L8.

You maybe will tell me, not to use Wheezy packages on Jessie. But at least you should fix you dependencies. The truth is, with ```libjpeg62-turbo``` your dependencies are satisfied but you linked your wheezy packages against ```libjpeg8```.

**Comment by wagnert** [comment]
We'll have a look at it tomorrow, thanks :)

**Comment by zelgerj** [comment]
Hi waja, yes you're totally right. We'll fix the dependency from ```libjpeg8```to ```libjpeg62-turbo```as soon as possible for the debian 8 (jessie).

**Comment by zelgerj** [comment]
i've removed our deprecated docker images for 1.0.5 & 1.0.6. We'll update them in the near future. The base of those docker-images was ubuntu:latest and no debian:jessie...

To fix your problem you should do:
```bash
# BEGIN (if you have an installed appserver running)
    systemctl stop appserver
    systemctl stop appserver-php5-fpm
    systemctl stop appserver-watcher
    aptitude purge appserver-dist appserver-runtime
    rm -rf /opt/appserver
# END

rm -f /etc/apt/sources.list.d/appserver.list
echo "deb http://deb.appserver.io/ jessie main" > /etc/apt/sources.list.d/appserver.list && \
      wget http://deb.appserver.io/appserver.gpg -O - | apt-key add -
apt-get -y update
apt-get install -y appserver-dist
```

Successfully tested on a fresh debian jessie.

**Comment by wick-ed** [comment]
Hi @waja ,

do you still experience problems? Dependencies should have been updated.
We would like to close the issue otherwise.

Regards,

Bernhard

**Comment by waja** [comment]
@wick-ed On a fresh jessie (docker) image a ```apt-get install --no-install-recommends -y appserver-dist``` results into:

```
Setting up appserver-dist (1.1.0-31) ...
Failed to get D-Bus connection: Unknown error -1
dpkg: error processing package appserver-dist (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.19-18+deb8u1) ...
Errors were encountered while processing:
 appserver-dist
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by wick-ed** [comment]
Thanks.

This would most likely relate to this issue #911?
I would close this one then, as the issue seems to be the `systemctl` integration within docker as laid out by Johann in #911 
We are currently in the process to refactor our docker images (not top priority though :( ). This might fix this issue.

Regards,

Bernhard

**Comment by waja** [comment]
As the package wasn't able to be installed, I can't confirm, that the ```shared object file``` problem is fixed with latest package.

**Comment by wick-ed** [comment]
I do see.
Can we go with re-opening the issue if the problem would come up again?
Why did you test with the Wheezy package in the first place?
We do offer specific Jessie packages (which share the `control` file with Wheezy though).

I do not understand why the missing `libjpeg8` would be a problem here.

**Comment by waja** [comment]
The issue was, that you rely on a shared library ```libjpeg.so.8```, but this is not reflected in your package dependencies. If you rely on such a library, you need depend on the (Debian) package containing this file.

**Comment by wick-ed** [comment]
I see. Did you try the Jessie package?

**Comment by waja** [comment]
Yes, I did. Just in docker: https://github.com/appserver-io/appserver/issues/910#issuecomment-168979102

**Comment by Quix0r** [comment]
In README.md there should be mentioned that Jessie requires an other package list due to `libjpeg.so.8`.

This one works on latest Jessie:
https://github.com/appserver-io/appserver/issues/910#issuecomment-153636762
