### ISSUE TITLE
[appserver-io/appserver] Varnish cannot reach the default server

### ISSUE THREAD

**Issue by ksaltik** [appserver-io/appserver#928]
[appserver-io/appserver] Varnish cannot reach the default server with 0.0.0.0 mask.
And I get a warning without finishing the test in Google Pagespeed Insights.
How to use the Servlet Engine with magento...

**Comment by wick-ed** [comment]
Hi there @ksaltik ,

these are quite some issues you will need to elaborate a little more. :)

Which appserver version are you using and which host OS are you on?

What do you mean by "cannot reach the default server"? Did you try to configure the appserver as a backend for varnish? Please be aware that appserver runs on port `9080` per default.
See also http://appserver.io/get-started/documentation/1.0/basic-usage.html

What warning do you get? Is the warning related to an application you deployed or to e.g. the example application we ship?

Servlet usage together with what we call "legacy application" (see http://appserver.io/get-started/documentation/1.0/webapps.html) is not that easy and often does not yield significant rewards as most PHP applications simply are not built to be used in a stateful manner.
We DID on the other hand experiment with Magento wrapped in servlets and did experience performance increases.
But we did not continue on this as other projects took our time.
You might have a look here though:
https://github.com/appserver-io-lab/magento-wrapper
https://github.com/appserver-io-lab/mage-servlet

Hope this helps for a start. If you answer my questions I am sure we can further help you.
You might also join our support chat at https://gitter.im/appserver-io/appserver

Regards,

Bernhard

**Comment by ksaltik** [comment]
Our OS is Debian Jessie on Google Cloud Platform. We configure Varnish backend to listen port 9080. The warning we get is the host is unreachable. By the time we use appserver with HHVM. Its speed is as fast as a hhvm+nginx+varnish+redis server stack without redis+varnish. After adding redis+varnish to this stuck we can't imagine how fast will be our server.

Also I get warning from Google Pagespeed Insight test. 
Decoding the main resource failed. Please ensure that the page loads properly in a browser.

Our demo site is http://appserver.oneyhosting.com/

Also there is one more problem but it is related to HHVM we think high CPU usage during AB Benchmark test.

When we solve this problems we will plan to replace nginx with appserver.
So we need your support.

Regards
Kenan

**Comment by wick-ed** [comment]
Hi Kenan,

this sounds (and looks) very promising!

The pagespeed is related to your appserver demo site then?
We did not make tests with varnish so far but will do to support you in your project.
Do you mind posting the key parts of your varnish configuration for us to better reproduce the issue?

You can always get support over an issue or the mentioned chat if you need it.
We will help you as soon as we can arrange it.
For better integration you might also check out our parter program: http://zelgerj.appserver.io/partners.html

I will come back to you when we were able to find something.

Regards,

Bernhard

**Comment by wick-ed** [comment]
Hi @ksaltik ,

I just made some tests with a simple varnish tests and could not reproduce your problem.
- appserver version: 1.1.0
- varnish version: 4.0.3
The setup worked from the start with the only change to the port within the `/etc/varnish/default.vcl` from `8080` to `9080`.
Could you further specify the problem you are having and post your `appserver.xml` and varnish config?

Regards,
Bernhard 

PS.: The pagespeed issue could be reproduced with some(!) other sites hosted on appserver.io. But it does not seem to be a general issue. Will investigate further

**Comment by ksaltik** [comment]
Thank you I will retry it later. At the moment I remove the server from cloud and reinstall it. I cannot send the appserver.xml and varnish config file. I will try it with php7 because hhvm has issues it fails use all CPU resources. And I will try to implement the magento servlet. So I can make some speed test.

**Comment by wick-ed** [comment]
Hi @ksaltik 

any news on this issue?
Were you able to test again with your varnish setup?

Regards,

Bernhard

**Comment by wick-ed** [comment]
Hi @ksaltik ,

I will close this issue for being stale for a while.
If you are still experiencing problems with this or need support in regards to this issue feel free to re-open. :)

Regards,

Bernhard
