### ISSUE TITLE
[appserver-io/appserver] 1.2.0 Iron IDontKnowWhatWeAreSupposedToDo :D

### ISSUE THREAD

**Issue by smolinari** [appserver-io/appserver#939]
Suggestions?

1.2.0 Iron Shield

or. 

1.2.0 Iron Sabre

or

1.2.0 Iron Pike

or 

1.2.0 Iron Lance

or 

1.2.0 Iron Bow

:smile: 

Scott

**Comment by wick-ed** [comment]
Hi @smolinari ,

good ones! ^^
Keep them comming :+1:

**Comment by wick-ed** [comment]
We got some more complex things in mind, like Iron Castle or Iron Dragon ^^

**Comment by wick-ed** [comment]
Hi @smolinari ,

we discussed the issue internally and came to the conclusion that we would like to offer the honor of naming the next release to you. :)

You have been (and hopefully will stay) one of our dearest followers and already did a lot for the project as a whole. Alone your blog posts were an enormous help!

So like I said: keep them coming and tell us which one you would favor :)
We would still keep our veto though for marketing reasons to not be forced to release an Iron Willy or something of the sort. ^^ ;)

So go for it! :-D

**Comment by smolinari** [comment]
Wow. Thanks. That is an honor. 

I've been thinking some more about it and the name needs a decent logo too (which you've done a great job with in the past, btw), and just the weapon ideas could be a bit boring for the logo. Though, the names sound really good, like "Iron Crossbow" or "Iron Sabre". Hmm....Iron Dragon could make for a cool logo for sure. I am liking the name "Iron Crossbow" more and more, as I think more about a good name.....

Hmmm....decisions.....decisions. :smile: 

Scott

**Comment by wick-ed** [comment]
Hehe, you are welcome. ^^ 

Given the flood of issues I am sure you have some time on your hands to ponder upon it. ;)
Logo praise will be forwarded to our designer. :)

**Comment by zelgerj** [comment]
Hi @smolinari,

have you had the opportunity to make a final decision? :)

As we need to make some preparations for our next release it would be great if you could give us feedback soon without producing any pressure ;)

Thanks!

**Comment by smolinari** [comment]
What is the overall goal of 1.2.0? Anything in particular? 

Scott

**Comment by zelgerj** [comment]
i just updated our roadmap containing the overall goals of 1.2.0.
http://appserver.io/products/roadmap.html

**Comment by smolinari** [comment]
:smile: Then definitely Iron Dragon! :+1: 

Scott

**Comment by zelgerj** [comment]
All right! :+1:
Let's try to get your Iron Dragon in the air as soon as possible ;)

Thanks for that cool release name!

**Comment by smolinari** [comment]
Thanks for a cool software!

Scott

**Comment by wick-ed** [comment]
:+1:
