### ISSUE TITLE
[appserver-io/appserver] Allow different environments aka stages with corresponding configuration

### ISSUE THREAD

**Issue by akleiber** [appserver-io/appserver#940]
To quickly explain what this issue is about I am quoting [Symfony](http://symfony.com/doc/current/cookbook/configuration/environments.html) here:
> Every application is the combination of code and a set of configuration that dictates how that code should function. The configuration may define the database being used, if something should be cached or how verbose logging should be.

The simplest use case would be to have different hosts for an applications datasources for the different environments (development, testing, production).

Another use case would be to execute different provisioners for the different stages. Or to make provisioners behave differently for the different stages. 
I.e. for the development environment I want a provisioner to always create a default database entry in the admin table with username admin and password admin when the entry does not exist. But in production I want the password to be something more secure.

@wagnert We talked about this on gitter this morning. I can add some more use cases if you'd like me to.

**Comment by smolinari** [comment]
I can add a usecase too, I think. A form of PaaS appserver environment, where each virtual host is hosting different customers, with different database access, different applications and extensions, etc. Then also a provisioning system, so copies or "Sandboxes" of the appserver "environments" can be created. I'm not too sure how much of that would be appserver responsibility, but if it can happen within single appservers, it would be really cool. :wink: 

Scott

**Comment by wick-ed** [comment]
Possible implementation might be along the lines of `dotenv`: see https://github.com/vlucas/phpdotenv
This would utilize a special way to map sensitive data.

**Comment by smolinari** [comment]
Yes, that sounds like a step in the right direction to me. :+1: 

Scott
