### ISSUE TITLE
[appserver-io/doppelgaenger] Inline Functions in Session Beans 

### ISSUE THREAD

**Issue by wagnert** [appserver-io/appserver#943]
It actually seems, that inline functions in Session Beans do not work, because Doppelgaenger tries to create a `DOPPELGAENGEROriginal` function for that. For example, you've an inline function like
```php
// this is necessary to load the PSR-4 compatible Swagger library
\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader(function($className) use ($application) {
        // load the application directory
        $webappPath = $application->getWebappPath();
        ...
});
```
Doppelgaenger libraries generates a function like
```php
public function ( $visitor, Tobscure\JsonApi\Document $obj, array $type)
{
    ...
}
```
which results in something like
```sh
[26-Dec-2015 20:33:52 Europe/Berlin] PHP Parse error:  syntax error, unexpected '(', expecting identifier (T_STRING) in /opt/appserver/var/tmp/api/cache/AppserverIo_Apps_Api_Encoder_JmsSerializerEncoder.php on line 139
```
If you need an example, feel free to checkout the appserver.io API implementation from my [fork](https://github.com/wagnert/api).

**Comment by wick-ed** [comment]
Solved with https://github.com/appserver-io/doppelgaenger/releases/tag/1.5.1
