### ISSUE TITLE
Laravel 5.1 project on appserver.io

### ISSUE THREAD

**Issue by kailashgajara** [appserver-io/appserver#974]
Hi,

I have placed my laravel project under /opt/appserver/webapps/myproject. When I try to access the project http://localhost:9080/myproject/, I get following error. I guess it has something to do with redirect engine. The project works just fine in apache. 

The requested URL /myproject/ was not found on this server.

exception 'AppserverIo\Server\Exceptions\ModuleException' with message 'The requested URL /myproject/ was not found on this server.' in /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/Modules/CoreModule.php:268

Stack trace:

#0 /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/ConnectionHandlers/HttpConnectionHandler.php(507): AppserverIo\WebServer\Modules\CoreModule->process(Object(AppserverIo\Http\HttpRequest), Object(AppserverIo\Http\HttpResponse), Object(AppserverIo\Server\Contexts\RequestContext), 2)

#1 /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/ConnectionHandlers/HttpConnectionHandler.php(433): AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler->processModules(2)

#2 /opt/appserver/vendor/appserver-io/server/src/AppserverIo/Server/Workers/ThreadWorker.php(256): AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler->handle(Object(AppserverIo\Server\Sockets\StreamSocket), Object(AppserverIo\Server\Workers\ThreadWorker))

#3 /opt/appserver/vendor/appserver-io/server/src/AppserverIo/Server/Workers/ThreadWorker.php(183): AppserverIo\Server\Workers\ThreadWorker->work()

#4 {main}

**Comment by wick-ed** [comment]
Hi there @kailashgajara ,

what does the `myproject` folder contain? Our webserver would look for an index file like `index.html` or `index.php`. Without any configured rewrites the rewrite engine should not influence the process at all.
Problem is we do not pick up `.htaccess` files like apache does. So we might miss some rewrites here.
How would your apache setup look? Any rewrites in `.htaccess`?

Regards,

Bernhard

**Comment by wick-ed** [comment]
Does http://localhost:9080/myproject/index.php show anything?

**Comment by kailashgajara** [comment]
@wick-ed Thanks for your answer. Ya, I got that now. I had to add virtual-host in virtual-hosts.xml file. We can close this now.

On a side note: Sorry for very basic question but I have my laravel project. I add pdo-mysql.so in php.ini but I'm getting error as below:

[17-Mar-2016 08:32:13 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/appserver/lib/php/extensions/no-debug-zts-20131226/pdo-mysql.so' - dlopen(/opt/appserver/lib/php/extensions/no-debug-zts-20131226/pdo-mysql.so, 9): image not found in Unknown on line 0

**Comment by wick-ed** [comment]
Cool @kailashgajara  :)

Do you have a file `/opt/appserver/lib/php/extensions/no-debug-zts-20131226/pdo-mysql.so`?
This extension is not included by default so you might have to install it using the appserver `pecl` at `/opt/appserver/bin`.

**Comment by wick-ed** [comment]
Btw. we do have a support chat over at gitter: https://gitter.im/appserver-io/appserver
You might join if you have any other questions on appserver.io :)
